### ISSUE TITLE
Improvement - Mark the redundant/invalid input with the colour to ease the user fixing the mistake.

### ISSUE THREAD

**Issue by kerrambit** [Jakubisek/C-SSG#10]
**Improvement - Mark the redundant/invalid input with the colour to ease the user fixing the mistake.**

**Steps:**

1. Run the app.
2. Enter invalid input "890075040*39*5030*660002*31008001932009004*5*42*4500081070*27*34*2".
3. Warning message that pops up: "Warning: input contains redundant data, ignoring everything from '*' at 64.", could contain the entered input with marked symbols that are redundant.

![obrazek](https://github.com/Jakubisek/C-SSG/assets/108737044/011fb93d-e9df-4aac-b1f0-8fbeb4b72658)

**Comment by Jakubisek** [comment]
I have no idea why I did not think of that, thank you for the suggestion!
